In [100]:
import random
import numpy as np
from heapq import *

In [101]:
n=int(input('enter n:'))

enter n:8


In [102]:
def CreateFirstMatrice():
    Matrice = np.zeros((n,n), dtype=int)
    for row in range(n):
        rand=random.randint(0,(n-1))
        for col in range(n):
            Matrice[row][col]=0 
        Matrice[row][rand]=1
    return Matrice

In [103]:
Matrice=CreateFirstMatrice()


In [104]:
def CaculateHeuristic(Matrice):
    SumAll=0
    SumRows=CaculateRows(Matrice)
    SumCols=CaculateCols(Matrice)
    SumDiagnoleRightRows=CaculateDiagnoleRightRows(Matrice)
    SumDiagnoleLefttRows=CaculateDiagnoleLeftRows(Matrice)
    SumDiagnoleRightCols=CaculateDiagnoleRightCols(Matrice)
    SumDiagnoleLeftCols=CaculateDiagnoleLeftCols(Matrice)

    SumAll=SumRows+SumCols+SumDiagnoleRightRows+SumDiagnoleLefttRows+SumDiagnoleRightCols+SumDiagnoleLeftCols
    return SumAll
        

In [105]:
def CaculateRows(Matrice):
    Sum=0
    for i in range(n):
        Queen=0
        for j in range(n):
            if Matrice[i][j]==1:
                Queen=Queen+1
        if Queen>=1:
            Sum=Sum+((Queen*(Queen-1))//2)
    return Sum

In [106]:
def CaculateCols(Matrice):
    Sum=0
    for j in range(n):
        Queen=0
        for i in range(n):
            if Matrice[i][j]==1:
                Queen=Queen+1
        if Queen>=1:
            Sum=Sum+((Queen*(Queen-1))//2)
    return Sum

In [107]:
def CaculateDiagnoleRightRows(Matrice):
    Sum=0
    for col in range(n):
        Queen=0
        j=col
        for i in range(n):
            if j>(n-1) :
                break
            if Matrice[i][j]==1:
                Queen=Queen+1
            j=j+1
        if Queen>=1:
            Sum=Sum+((Queen*(Queen-1))//2)
    return Sum

In [108]:
def CaculateDiagnoleLeftRows(Matrice):
    Sum=0
    for col in range((n-1),-1,-1):
        Queen=0
        j=col
        for i in range(n):
            if j<0:
                break
            if Matrice[i][j]==1:
                Queen=Queen+1
            j=j-1
        if Queen>=1:
            Sum=Sum+((Queen*(Queen-1))//2)
    return Sum

In [109]:
def CaculateDiagnoleRightCols(Matrice):
    Sum=0
    for row  in range(1,n,1):
        Queen=0
        i=row
        for j in range(n):
            if i>(n-1) :
                break
            if Matrice[i][j]==1:
                Queen=Queen+1
            i=i+1
        if Queen>=1:
            Sum=Sum+((Queen*(Queen-1))//2)
    return Sum
    

In [110]:
def CaculateDiagnoleLeftCols(Matrice):
    Sum=0
    for row  in range(1,n,1):
        Queen=0
        i=row
        for j in range((n-1),-1,-1):
            if i>(n-1) :
                break
            if Matrice[i][j]==1:
                Queen=Queen+1
            i=i+1
        if Queen>=1:
            Sum=Sum+((Queen*(Queen-1))//2)
    return Sum

In [111]:
h=[]
Dict={}
SeenMatrices=set()
def Search(Matrice):
    Heuristic=CaculateHeuristic(Matrice)
    print(f'Heuristic : {Heuristic}')
    PrintMatrice(Matrice)
    #for any rows we find out place of queen
    for row in range(n):
        OldCol=0
        for i in range(n):
            if Matrice[row][i]==1:
                OldCol=i
                break
        #moving queen forward and caculating heuristic and inserting to heap        
        col=(OldCol+1)
        while col<n:
            CopyMatrice = Matrice.copy()
            for i in range(n):
                CopyMatrice[row][i]=0  
            CopyMatrice[row][col]=1
            col=(col+1)
            Heuristic=CaculateHeuristic(CopyMatrice)
            Key=hash(str(CopyMatrice))
            Dict[Key]=CopyMatrice
            heappush(h, (Heuristic, hash(str(CopyMatrice))))

        #moving queen backward and caculating heuristic and inserting to heap 
        col=(OldCol-1)
        while col>=0:
            CopyMatrice = Matrice.copy()
            for i in range(n):
                CopyMatrice[row][i]=0  
            CopyMatrice[row][col]=1
            col=(col-1)
            Heuristic=CaculateHeuristic(CopyMatrice)
            Key=hash(str(CopyMatrice))
            Dict[Key]=CopyMatrice
            heappush(h, (Heuristic,Key))
    
    #pop unseen state from heap    
    Ans=heappop(h) 
    Key=Ans[1]
    while Key in SeenMatrices:
        Ans=heappop(h)
        Key=Ans[1]
    #add this state to SeenMatrices    
    SeenMatrices.add(Key)
    Heuristic=Ans[0]
    NewMatrice=Dict[Key]
    
    #goal check
    if Heuristic==0:
        print(f'Heuristice : {Heuristic}')
        PrintMatrice(NewMatrice)
    else:
        Search(NewMatrice)      

In [112]:
def PrintMatrice(Matrice):
    for i in Matrice:
        print(i)

In [113]:
Search(Matrice)

Heuristic : 9
[0 1 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0]
[0 0 1 0 0 0 0 0]
[0 1 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0]
[0 0 0 0 0 0 0 1]
[1 0 0 0 0 0 0 0]
Heuristic : 6
[0 1 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0]
[0 0 1 0 0 0 0 0]
[0 1 0 0 0 0 0 0]
[0 0 0 1 0 0 0 0]
[0 0 0 0 0 0 0 1]
[1 0 0 0 0 0 0 0]
Heuristic : 4
[0 0 0 0 1 0 0 0]
[1 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0]
[0 0 1 0 0 0 0 0]
[0 1 0 0 0 0 0 0]
[0 0 0 1 0 0 0 0]
[0 0 0 0 0 0 0 1]
[1 0 0 0 0 0 0 0]
Heuristic : 2
[0 0 0 0 1 0 0 0]
[1 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0]
[0 0 0 0 0 0 1 0]
[0 1 0 0 0 0 0 0]
[0 0 0 1 0 0 0 0]
[0 0 0 0 0 0 0 1]
[1 0 0 0 0 0 0 0]
Heuristic : 2
[0 0 0 0 1 0 0 0]
[1 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0]
[0 0 0 0 0 0 1 0]
[0 1 0 0 0 0 0 0]
[0 0 0 1 0 0 0 0]
[0 0 0 0 0 0 0 1]
[0 0 0 0 0 1 0 0]
Heuristic : 2
[0 0 0 0 1 0 0 0]
[1 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0]
[0 0 0 0 0 0 1 0]
[0 1 0 0 0 0 0 0]
[0 0 1 0 0 0 0 0]
[0 0 0 0 0 0 0 1]
[0 0 0 0 0 1 0 0]
Heuristic : 2
[0 0 1 0 0 0 0 0]
[1 0 0 0 0 0 0 0]
[0