In [1]:
import random
import numpy as np
from heapq import *

In [3]:
n=int(input('enter n:'))

enter n:8


In [4]:
def CreateFirstMatrix():
    Matrix = np.zeros((n,n), dtype=int)
    for row in range(n):
        rand=random.randint(0,(n-1))
        for col in range(n):
            Matrix[row][col]=0 
        Matrix[row][rand]=1
    return Matrix

In [5]:
Matrix=CreateFirstMatrix()


In [6]:
def CaculateHeuristic(Matrix):
    SumAll=0
    SumRows=CaculateRows(Matrix)
    SumCols=CaculateCols(Matrix)
    SumDiagnoleRightRows=CaculateDiagnoleRightRows(Matrix)
    SumDiagnoleLefttRows=CaculateDiagnoleLeftRows(Matrix)
    SumDiagnoleRightCols=CaculateDiagnoleRightCols(Matrix)
    SumDiagnoleLeftCols=CaculateDiagnoleLeftCols(Matrix)

    SumAll=SumRows+SumCols+SumDiagnoleRightRows+SumDiagnoleLefttRows+SumDiagnoleRightCols+SumDiagnoleLeftCols
    return SumAll
        

In [7]:
def CaculateRows(Matrix):
    Sum=0
    for i in range(n):
        Queen=0
        for j in range(n):
            if Matrix[i][j]==1:
                Queen=Queen+1
        if Queen>=1:
            Sum=Sum+((Queen*(Queen-1))//2)
    return Sum

In [8]:
def CaculateCols(Matrix):
    Sum=0
    for j in range(n):
        Queen=0
        for i in range(n):
            if Matrix[i][j]==1:
                Queen=Queen+1
        if Queen>=1:
            Sum=Sum+((Queen*(Queen-1))//2)
    return Sum

In [9]:
def CaculateDiagnoleRightRows(Matrix):
    Sum=0
    for col in range(n):
        Queen=0
        j=col
        for i in range(n):
            if j>(n-1) :
                break
            if Matrix[i][j]==1:
                Queen=Queen+1
            j=j+1
        if Queen>=1:
            Sum=Sum+((Queen*(Queen-1))//2)
    return Sum

In [10]:
def CaculateDiagnoleLeftRows(Matrix):
    Sum=0
    for col in range((n-1),-1,-1):
        Queen=0
        j=col
        for i in range(n):
            if j<0:
                break
            if Matrix[i][j]==1:
                Queen=Queen+1
            j=j-1
        if Queen>=1:
            Sum=Sum+((Queen*(Queen-1))//2)
    return Sum

In [11]:
def CaculateDiagnoleRightCols(Matrix):
    Sum=0
    for row  in range(1,n,1):
        Queen=0
        i=row
        for j in range(n):
            if i>(n-1) :
                break
            if Matrix[i][j]==1:
                Queen=Queen+1
            i=i+1
        if Queen>=1:
            Sum=Sum+((Queen*(Queen-1))//2)
    return Sum
    

In [12]:
def CaculateDiagnoleLeftCols(Matrix):
    Sum=0
    for row  in range(1,n,1):
        Queen=0
        i=row
        for j in range((n-1),-1,-1):
            if i>(n-1) :
                break
            if Matrix[i][j]==1:
                Queen=Queen+1
            i=i+1
        if Queen>=1:
            Sum=Sum+((Queen*(Queen-1))//2)
    return Sum

In [13]:
h=[]
Dict={}
SeenMatrixes=[]
def Search(Matrix):
    #for any rows we find out place of queen
    for row in range(n):
        OldCol=0
        #find out last place of queen
        for i in range(n):
            if Matrix[row][i]==1:
                OldCol=i
                break
        #########################
        #caculate heuristic for cols before oldcol 
        col=(OldCol+1)
        while col<n:
            CopyMatrix = Matrix.copy()
            for i in range(n):
                CopyMatrix[row][i]=0  
            CopyMatrix[row][col]=1
            col=(col+1)
            Heuristic=CaculateHeuristic(CopyMatrix)
            Key=hash(str(CopyMatrix))
            Dict[Key]=CopyMatrix
            heappush(h, (Heuristic, hash(str(CopyMatrix))))

        #caculate heuristic for cols after oldcol
        col=(OldCol-1)
        while col>=0:
            CopyMatrix = Matrix.copy()
            for i in range(n):
                CopyMatrix[row][i]=0  
            CopyMatrix[row][col]=1
            col=(col-1)
            Heuristic=CaculateHeuristic(CopyMatrix)
            Key=hash(str(CopyMatrix))
            Dict[Key]=CopyMatrix
            heappush(h, (Heuristic,Key))
        
    Ans=heappop(h) 
    Key=Ans[1]
    while Key in SeenMatrixes:
        Ans=heappop(h)
        Key=Ans[1]
        
    SeenMatrixes.append(Key)
    Heuristic=Ans[0]
    NewMatrix=Dict[Key]
    if Heuristic==0:
        print(f'Heuristice : {Heuristic}')
        PrintMatrix(NewMatrix)
    else:
        print(f'Heuristic : {Heuristic}')
        PrintMatrix(NewMatrix)
        Search(NewMatrix)      

In [14]:
def PrintMatrix(Matrix):
    for i in Matrix:
        print(i)

In [15]:
Search(Matrix)

Heuristic : 4
[0 0 0 0 0 0 0 1]
[0 0 0 0 0 0 0 1]
[0 0 1 0 0 0 0 0]
[1 0 0 0 0 0 0 0]
[0 0 0 0 0 1 0 0]
[0 1 0 0 0 0 0 0]
[0 1 0 0 0 0 0 0]
[0 0 0 0 0 1 0 0]
Heuristic : 3
[0 0 0 0 1 0 0 0]
[0 0 0 0 0 0 0 1]
[0 0 1 0 0 0 0 0]
[1 0 0 0 0 0 0 0]
[0 0 0 0 0 1 0 0]
[0 1 0 0 0 0 0 0]
[0 1 0 0 0 0 0 0]
[0 0 0 0 0 1 0 0]
Heuristic : 2
[0 0 0 0 1 0 0 0]
[0 0 0 0 0 0 0 1]
[0 0 1 0 0 0 0 0]
[1 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0]
[0 1 0 0 0 0 0 0]
[0 1 0 0 0 0 0 0]
[0 0 0 0 0 1 0 0]
Heuristic : 1
[0 0 0 0 1 0 0 0]
[0 0 0 0 0 0 0 1]
[0 0 0 1 0 0 0 0]
[1 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0]
[0 1 0 0 0 0 0 0]
[0 1 0 0 0 0 0 0]
[0 0 0 0 0 1 0 0]
Heuristic : 1
[0 0 0 0 1 0 0 0]
[0 0 0 0 0 0 0 1]
[0 0 0 1 0 0 0 0]
[1 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0]
[0 0 0 0 1 0 0 0]
[0 1 0 0 0 0 0 0]
[0 0 0 0 0 1 0 0]
Heuristic : 1
[0 0 0 0 1 0 0 0]
[0 0 0 0 0 0 0 1]
[0 0 0 1 0 0 0 0]
[1 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0]
[0 1 0 0 0 0 0 0]
[0 0 0 0 0 1 0 0]
[0 0 0 0 0 1 0 0]
Heuristice : 0
[0 0 0 0 1 0 0 0]
[0 0 0 0 0 0 0 1]
[